# Themes
colorscheme base16-sunburn
# Cursor focus hinting, would be better to change shape, but hey
hook global FocusIn .* %{ face global PrimaryCursor rgb:000000,rgb:CCCCCC+fg; face global PrimaryCursorEol PrimaryCursor}
hook global FocusOut .* %{ face global PrimaryCursor rgb:000000,rgb:CC8843+fg; face global PrimaryCursorEol PrimaryCursor}

# Display options
set-option global tabstop 4
set-option global indentwidth 0

# Hooks
# Remove trailing whitespace on save
hook global BufWritePre .* %{try %{exec -draft '%s\h+$<ret>d'}}

# Yank to clipboard
hook global NormalKey y|d|c %{ nop %sh{
	  printf %s "$kak_main_reg_dquote" | wl-copy > /dev/null 2>&1 &
}}

# Keybinds
# Shortcuts for use
map global normal <c-w> ': db<ret>'
# Tab auto-completion
hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p> }
# Shortcuts to enter normal mode
map global normal <ret> <i><ret>
map global normal <del> <a-c>
map global normal <backspace> <i><backspace>
# Arrow Movements
#map global normal <c-l> <w><\;>
#map global normal <c-h> <b><\;>
#map global normal <c-right> <w><\;>
#map global normal <c-left> <b><\;>
#Soft Wrapping
define-command softwarp-enable 'add-highlighter buffer/ wrap -word'
define-command softwarp-disable 'remove-highlighter buffer/wrap_-word'
# Commenting
map global normal '#' ': comment-line<ret>' -docstring 'comment line'
map global normal '<a-#>' ': comment-block<ret>' -docstring 'comment block'
# Latex spell checking
# source ~/.config/kak/rc/spell-tex.kak
map global normal <=> ': spell<ret>'
map global normal <+> ': spell-tex<ret>'
define-command spell-next-replace %{ try %{ spell-next; spell-replace } }
map global normal <minus> ': spell-next-replace<ret>'
